import type { ProtocolAction, TrancheHistoryCheckpoint } from '../api'
import { displayText } from './protocol'

export function buildTrancheHistoryCsv(
  actions: ProtocolAction[],
  checkpoints: TrancheHistoryCheckpoint[],
): string {
  const escape = (value: unknown) => `"${displayText(value, '').replaceAll('"', '""')}"`
  const rows = [
    [
      'recordType',
      'timestamp',
      'blockNumber',
      'blockHash',
      'actionType',
      'transactionHash',
      'account',
      'orderId',
      'principalUsdc',
      'navUsdc',
      'shareSupply',
      'assetsPerShare',
      'drawdownUsdc',
      'impairmentGapUsdc',
      'coverageRatioBps',
      'calculationVersion',
      'formulaIdentifier',
      'formula',
      'sourceScopes',
      'availability',
      'data',
      'units',
      'evidence',
    ],
    ...actions.map((action) => [
      'action',
      new Date(action.timestamp * 1000).toISOString(),
      action.blockNumber,
      action.blockHash,
      action.actionType,
      action.transactionHash,
      action.account,
      action.orderId,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      JSON.stringify(action.data),
      JSON.stringify(action.units),
      JSON.stringify(action.evidence),
    ]),
    ...checkpoints.map((checkpoint) => [
      'snapshot_checkpoint',
      new Date(checkpoint.timestamp * 1000).toISOString(),
      checkpoint.blockNumber,
      checkpoint.blockHash,
      null,
      null,
      null,
      null,
      checkpoint.principalUsdc,
      checkpoint.navUsdc,
      checkpoint.shareSupply,
      checkpoint.assetsPerShare,
      checkpoint.drawdownUsdc,
      checkpoint.impairmentGapUsdc,
      checkpoint.coverageRatioBps,
      checkpoint.calculationVersion,
      checkpoint.formulaIdentifier,
      JSON.stringify(checkpoint.formula),
      JSON.stringify(checkpoint.sourceScopes),
      JSON.stringify(checkpoint.availability),
      null,
      JSON.stringify(checkpoint.units),
      JSON.stringify(checkpoint.evidence),
    ]),
  ]
  return rows.map((row) => row.map(escape).join(',')).join('\n')
}
